//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.24 at 04:53:17 PM BRST 
//


package br.inf.portalfiscal.nfe;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * Tipo Dados do Endereço do Emitente  // 24/10/08 - desmembrado / tamanho mínimo
 * 
 * <p>Java class for TEnderEmi complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TEnderEmi">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="xLgr">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.portalfiscal.inf.br/nfe}TString">
 *               &lt;maxLength value="60"/>
 *               &lt;minLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nro">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.portalfiscal.inf.br/nfe}TString">
 *               &lt;maxLength value="60"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="xCpl" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.portalfiscal.inf.br/nfe}TString">
 *               &lt;maxLength value="60"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="xBairro">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.portalfiscal.inf.br/nfe}TString">
 *               &lt;maxLength value="60"/>
 *               &lt;minLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="cMun" type="{http://www.portalfiscal.inf.br/nfe}TCodMunIBGE"/>
 *         &lt;element name="xMun">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.portalfiscal.inf.br/nfe}TString">
 *               &lt;maxLength value="60"/>
 *               &lt;minLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="UF" type="{http://www.portalfiscal.inf.br/nfe}TUfEmi"/>
 *         &lt;element name="CEP">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;whiteSpace value="preserve"/>
 *               &lt;pattern value="[0-9]{8}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="cPais" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.portalfiscal.inf.br/nfe}TString">
 *               &lt;enumeration value="1058"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="xPais" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.portalfiscal.inf.br/nfe}TString">
 *               &lt;enumeration value="Brasil"/>
 *               &lt;enumeration value="BRASIL"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="fone" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;whiteSpace value="preserve"/>
 *               &lt;pattern value="[0-9]{6,14}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TEnderEmi", propOrder = {
    "xLgr",
    "nro",
    "xCpl",
    "xBairro",
    "cMun",
    "xMun",
    "uf",
    "cep",
    "cPais",
    "xPais",
    "fone"
})
@Entity(name = "TEnderEmi")
@Table(name = "TENDEREMI")
@Inheritance(strategy = InheritanceType.JOINED)
public class TEnderEmi
    implements Equals, HashCode
{

    @XmlElement(required = true)
    protected String xLgr;
    @XmlElement(required = true)
    protected String nro;
    protected String xCpl;
    @XmlElement(required = true)
    protected String xBairro;
    @XmlElement(required = true)
    protected String cMun;
    @XmlElement(required = true)
    protected String xMun;
    @XmlElement(name = "UF", required = true)
    protected TUfEmi uf;
    @XmlElement(name = "CEP", required = true)
    protected String cep;
    protected String cPais;
    protected String xPais;
    protected String fone;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;

    /**
     * Gets the value of the xLgr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "XLGR", length = 60)
    public String getXLgr() {
        return xLgr;
    }

    /**
     * Sets the value of the xLgr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXLgr(String value) {
        this.xLgr = value;
    }

    /**
     * Gets the value of the nro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "NRO", length = 60)
    public String getNro() {
        return nro;
    }

    /**
     * Sets the value of the nro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNro(String value) {
        this.nro = value;
    }

    /**
     * Gets the value of the xCpl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "XCPL", length = 60)
    public String getXCpl() {
        return xCpl;
    }

    /**
     * Sets the value of the xCpl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXCpl(String value) {
        this.xCpl = value;
    }

    /**
     * Gets the value of the xBairro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "XBAIRRO", length = 60)
    public String getXBairro() {
        return xBairro;
    }

    /**
     * Sets the value of the xBairro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXBairro(String value) {
        this.xBairro = value;
    }

    /**
     * Gets the value of the cMun property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "CMUN", length = 255)
    public String getCMun() {
        return cMun;
    }

    /**
     * Sets the value of the cMun property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCMun(String value) {
        this.cMun = value;
    }

    /**
     * Gets the value of the xMun property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "XMUN", length = 60)
    public String getXMun() {
        return xMun;
    }

    /**
     * Sets the value of the xMun property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXMun(String value) {
        this.xMun = value;
    }

    /**
     * Gets the value of the uf property.
     * 
     * @return
     *     possible object is
     *     {@link TUfEmi }
     *     
     */
    @Basic
    @Column(name = "UF", length = 255)
    @Enumerated(EnumType.STRING)
    public TUfEmi getUF() {
        return uf;
    }

    /**
     * Sets the value of the uf property.
     * 
     * @param value
     *     allowed object is
     *     {@link TUfEmi }
     *     
     */
    public void setUF(TUfEmi value) {
        this.uf = value;
    }

    /**
     * Gets the value of the cep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "CEP")
    public String getCEP() {
        return cep;
    }

    /**
     * Sets the value of the cep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCEP(String value) {
        this.cep = value;
    }

    /**
     * Gets the value of the cPais property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "CPAIS")
    public String getCPais() {
        return cPais;
    }

    /**
     * Sets the value of the cPais property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPais(String value) {
        this.cPais = value;
    }

    /**
     * Gets the value of the xPais property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "XPAIS")
    public String getXPais() {
        return xPais;
    }

    /**
     * Sets the value of the xPais property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXPais(String value) {
        this.xPais = value;
    }

    /**
     * Gets the value of the fone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "FONE")
    public String getFone() {
        return fone;
    }

    /**
     * Sets the value of the fone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFone(String value) {
        this.fone = value;
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof TEnderEmi)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final TEnderEmi that = ((TEnderEmi) object);
        {
            String lhsXLgr;
            lhsXLgr = this.getXLgr();
            String rhsXLgr;
            rhsXLgr = that.getXLgr();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "xLgr", lhsXLgr), LocatorUtils.property(thatLocator, "xLgr", rhsXLgr), lhsXLgr, rhsXLgr)) {
                return false;
            }
        }
        {
            String lhsNro;
            lhsNro = this.getNro();
            String rhsNro;
            rhsNro = that.getNro();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "nro", lhsNro), LocatorUtils.property(thatLocator, "nro", rhsNro), lhsNro, rhsNro)) {
                return false;
            }
        }
        {
            String lhsXCpl;
            lhsXCpl = this.getXCpl();
            String rhsXCpl;
            rhsXCpl = that.getXCpl();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "xCpl", lhsXCpl), LocatorUtils.property(thatLocator, "xCpl", rhsXCpl), lhsXCpl, rhsXCpl)) {
                return false;
            }
        }
        {
            String lhsXBairro;
            lhsXBairro = this.getXBairro();
            String rhsXBairro;
            rhsXBairro = that.getXBairro();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "xBairro", lhsXBairro), LocatorUtils.property(thatLocator, "xBairro", rhsXBairro), lhsXBairro, rhsXBairro)) {
                return false;
            }
        }
        {
            String lhsCMun;
            lhsCMun = this.getCMun();
            String rhsCMun;
            rhsCMun = that.getCMun();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "cMun", lhsCMun), LocatorUtils.property(thatLocator, "cMun", rhsCMun), lhsCMun, rhsCMun)) {
                return false;
            }
        }
        {
            String lhsXMun;
            lhsXMun = this.getXMun();
            String rhsXMun;
            rhsXMun = that.getXMun();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "xMun", lhsXMun), LocatorUtils.property(thatLocator, "xMun", rhsXMun), lhsXMun, rhsXMun)) {
                return false;
            }
        }
        {
            TUfEmi lhsUF;
            lhsUF = this.getUF();
            TUfEmi rhsUF;
            rhsUF = that.getUF();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "uf", lhsUF), LocatorUtils.property(thatLocator, "uf", rhsUF), lhsUF, rhsUF)) {
                return false;
            }
        }
        {
            String lhsCEP;
            lhsCEP = this.getCEP();
            String rhsCEP;
            rhsCEP = that.getCEP();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "cep", lhsCEP), LocatorUtils.property(thatLocator, "cep", rhsCEP), lhsCEP, rhsCEP)) {
                return false;
            }
        }
        {
            String lhsCPais;
            lhsCPais = this.getCPais();
            String rhsCPais;
            rhsCPais = that.getCPais();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "cPais", lhsCPais), LocatorUtils.property(thatLocator, "cPais", rhsCPais), lhsCPais, rhsCPais)) {
                return false;
            }
        }
        {
            String lhsXPais;
            lhsXPais = this.getXPais();
            String rhsXPais;
            rhsXPais = that.getXPais();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "xPais", lhsXPais), LocatorUtils.property(thatLocator, "xPais", rhsXPais), lhsXPais, rhsXPais)) {
                return false;
            }
        }
        {
            String lhsFone;
            lhsFone = this.getFone();
            String rhsFone;
            rhsFone = that.getFone();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "fone", lhsFone), LocatorUtils.property(thatLocator, "fone", rhsFone), lhsFone, rhsFone)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            String theXLgr;
            theXLgr = this.getXLgr();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "xLgr", theXLgr), currentHashCode, theXLgr);
        }
        {
            String theNro;
            theNro = this.getNro();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "nro", theNro), currentHashCode, theNro);
        }
        {
            String theXCpl;
            theXCpl = this.getXCpl();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "xCpl", theXCpl), currentHashCode, theXCpl);
        }
        {
            String theXBairro;
            theXBairro = this.getXBairro();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "xBairro", theXBairro), currentHashCode, theXBairro);
        }
        {
            String theCMun;
            theCMun = this.getCMun();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "cMun", theCMun), currentHashCode, theCMun);
        }
        {
            String theXMun;
            theXMun = this.getXMun();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "xMun", theXMun), currentHashCode, theXMun);
        }
        {
            TUfEmi theUF;
            theUF = this.getUF();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "uf", theUF), currentHashCode, theUF);
        }
        {
            String theCEP;
            theCEP = this.getCEP();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "cep", theCEP), currentHashCode, theCEP);
        }
        {
            String theCPais;
            theCPais = this.getCPais();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "cPais", theCPais), currentHashCode, theCPais);
        }
        {
            String theXPais;
            theXPais = this.getXPais();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "xPais", theXPais), currentHashCode, theXPais);
        }
        {
            String theFone;
            theFone = this.getFone();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "fone", theFone), currentHashCode, theFone);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
