//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.24 at 04:53:17 PM BRST 
//


package br.inf.portalfiscal.nfe;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;
import org.w3._2000._09.xmldsig_.SignatureType;

/**
 * Tipo Protocolo de status resultado do processamento da NF-e
 * 
 * <p>Java class for TProtNFe complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TProtNFe">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="infProt">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="tpAmb" type="{http://www.portalfiscal.inf.br/nfe}TAmb"/>
 *                   &lt;element name="verAplic" type="{http://www.portalfiscal.inf.br/nfe}TVerAplic"/>
 *                   &lt;element name="chNFe" type="{http://www.portalfiscal.inf.br/nfe}TChNFe"/>
 *                   &lt;element name="dhRecbto" type="{http://www.portalfiscal.inf.br/nfe}TDateTimeUTC"/>
 *                   &lt;element name="nProt" type="{http://www.portalfiscal.inf.br/nfe}TProt" minOccurs="0"/>
 *                   &lt;element name="digVal" type="{http://www.w3.org/2000/09/xmldsig#}DigestValueType" minOccurs="0"/>
 *                   &lt;element name="cStat" type="{http://www.portalfiscal.inf.br/nfe}TStat"/>
 *                   &lt;element name="xMotivo" type="{http://www.portalfiscal.inf.br/nfe}TMotivo"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}Signature" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="versao" use="required" type="{http://www.portalfiscal.inf.br/nfe}TVerNFe" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TProtNFe", propOrder = {
    "infProt",
    "signature"
})
@Entity(name = "TProtNFe")
@Table(name = "TPROTNFE")
@Inheritance(strategy = InheritanceType.JOINED)
public class TProtNFe
    implements Equals, HashCode
{

    @XmlElement(required = true)
    protected TProtNFe.InfProt infProt;
    @XmlElement(name = "Signature", namespace = "http://www.w3.org/2000/09/xmldsig#")
    protected SignatureType signature;
    @XmlAttribute(name = "versao", required = true)
    protected String versao;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;

    /**
     * Gets the value of the infProt property.
     * 
     * @return
     *     possible object is
     *     {@link TProtNFe.InfProt }
     *     
     */
    @ManyToOne(targetEntity = TProtNFe.InfProt.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "INFPROT_TPROTNFE_HJID")
    public TProtNFe.InfProt getInfProt() {
        return infProt;
    }

    /**
     * Sets the value of the infProt property.
     * 
     * @param value
     *     allowed object is
     *     {@link TProtNFe.InfProt }
     *     
     */
    public void setInfProt(TProtNFe.InfProt value) {
        this.infProt = value;
    }

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureType }
     *     
     */
    @ManyToOne(targetEntity = SignatureType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "SIGNATURE_TPROTNFE_HJID")
    public SignatureType getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureType }
     *     
     */
    public void setSignature(SignatureType value) {
        this.signature = value;
    }

    /**
     * Gets the value of the versao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "VERSAO", length = 255)
    public String getVersao() {
        return versao;
    }

    /**
     * Sets the value of the versao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersao(String value) {
        this.versao = value;
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof TProtNFe)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final TProtNFe that = ((TProtNFe) object);
        {
            TProtNFe.InfProt lhsInfProt;
            lhsInfProt = this.getInfProt();
            TProtNFe.InfProt rhsInfProt;
            rhsInfProt = that.getInfProt();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "infProt", lhsInfProt), LocatorUtils.property(thatLocator, "infProt", rhsInfProt), lhsInfProt, rhsInfProt)) {
                return false;
            }
        }
        {
            SignatureType lhsSignature;
            lhsSignature = this.getSignature();
            SignatureType rhsSignature;
            rhsSignature = that.getSignature();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "signature", lhsSignature), LocatorUtils.property(thatLocator, "signature", rhsSignature), lhsSignature, rhsSignature)) {
                return false;
            }
        }
        {
            String lhsVersao;
            lhsVersao = this.getVersao();
            String rhsVersao;
            rhsVersao = that.getVersao();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "versao", lhsVersao), LocatorUtils.property(thatLocator, "versao", rhsVersao), lhsVersao, rhsVersao)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            TProtNFe.InfProt theInfProt;
            theInfProt = this.getInfProt();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "infProt", theInfProt), currentHashCode, theInfProt);
        }
        {
            SignatureType theSignature;
            theSignature = this.getSignature();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "signature", theSignature), currentHashCode, theSignature);
        }
        {
            String theVersao;
            theVersao = this.getVersao();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "versao", theVersao), currentHashCode, theVersao);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="tpAmb" type="{http://www.portalfiscal.inf.br/nfe}TAmb"/>
     *         &lt;element name="verAplic" type="{http://www.portalfiscal.inf.br/nfe}TVerAplic"/>
     *         &lt;element name="chNFe" type="{http://www.portalfiscal.inf.br/nfe}TChNFe"/>
     *         &lt;element name="dhRecbto" type="{http://www.portalfiscal.inf.br/nfe}TDateTimeUTC"/>
     *         &lt;element name="nProt" type="{http://www.portalfiscal.inf.br/nfe}TProt" minOccurs="0"/>
     *         &lt;element name="digVal" type="{http://www.w3.org/2000/09/xmldsig#}DigestValueType" minOccurs="0"/>
     *         &lt;element name="cStat" type="{http://www.portalfiscal.inf.br/nfe}TStat"/>
     *         &lt;element name="xMotivo" type="{http://www.portalfiscal.inf.br/nfe}TMotivo"/>
     *       &lt;/sequence>
     *       &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}ID" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tpAmb",
        "verAplic",
        "chNFe",
        "dhRecbto",
        "nProt",
        "digVal",
        "cStat",
        "xMotivo"
    })
    @Entity(name = "TProtNFe$InfProt")
    @Table(name = "INFPROT")
    @Inheritance(strategy = InheritanceType.JOINED)
    public static class InfProt
        implements Equals, HashCode
    {

        @XmlElement(required = true)
        protected String tpAmb;
        @XmlElement(required = true)
        protected String verAplic;
        @XmlElement(required = true)
        protected String chNFe;
        @XmlElement(required = true)
        protected String dhRecbto;
        protected String nProt;
        protected byte[] digVal;
        @XmlElement(required = true)
        protected String cStat;
        @XmlElement(required = true)
        protected String xMotivo;
        @XmlAttribute(name = "Id")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        @XmlSchemaType(name = "ID")
        protected String id;
        @XmlAttribute(name = "Hjid")
        protected Long hjid;

        /**
         * Gets the value of the tpAmb property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Basic
        @Column(name = "TPAMB", length = 255)
        public String getTpAmb() {
            return tpAmb;
        }

        /**
         * Sets the value of the tpAmb property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTpAmb(String value) {
            this.tpAmb = value;
        }

        /**
         * Gets the value of the verAplic property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Basic
        @Column(name = "VERAPLIC", length = 20)
        public String getVerAplic() {
            return verAplic;
        }

        /**
         * Sets the value of the verAplic property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVerAplic(String value) {
            this.verAplic = value;
        }

        /**
         * Gets the value of the chNFe property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Basic
        @Column(name = "CHNFE", length = 44)
        public String getChNFe() {
            return chNFe;
        }

        /**
         * Sets the value of the chNFe property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChNFe(String value) {
            this.chNFe = value;
        }

        /**
         * Gets the value of the dhRecbto property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Basic
        @Column(name = "DHRECBTO", length = 255)
        public String getDhRecbto() {
            return dhRecbto;
        }

        /**
         * Sets the value of the dhRecbto property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDhRecbto(String value) {
            this.dhRecbto = value;
        }

        /**
         * Gets the value of the nProt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Basic
        @Column(name = "NPROT", length = 15)
        public String getNProt() {
            return nProt;
        }

        /**
         * Sets the value of the nProt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNProt(String value) {
            this.nProt = value;
        }

        /**
         * Gets the value of the digVal property.
         * 
         * @return
         *     possible object is
         *     byte[]
         */
        @Basic
        @Column(name = "DIGVAL")
        @Lob
        public byte[] getDigVal() {
            return digVal;
        }

        /**
         * Sets the value of the digVal property.
         * 
         * @param value
         *     allowed object is
         *     byte[]
         */
        public void setDigVal(byte[] value) {
            this.digVal = value;
        }

        /**
         * Gets the value of the cStat property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Basic
        @Column(name = "CSTAT", length = 3)
        public String getCStat() {
            return cStat;
        }

        /**
         * Sets the value of the cStat property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCStat(String value) {
            this.cStat = value;
        }

        /**
         * Gets the value of the xMotivo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Basic
        @Column(name = "XMOTIVO", length = 255)
        public String getXMotivo() {
            return xMotivo;
        }

        /**
         * Sets the value of the xMotivo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setXMotivo(String value) {
            this.xMotivo = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @Basic
        @Column(name = "ID", length = 255)
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the hjid property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        @Id
        @Column(name = "HJID")
        @GeneratedValue(strategy = GenerationType.AUTO)
        public Long getHjid() {
            return hjid;
        }

        /**
         * Sets the value of the hjid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setHjid(Long value) {
            this.hjid = value;
        }

        public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
            if (!(object instanceof TProtNFe.InfProt)) {
                return false;
            }
            if (this == object) {
                return true;
            }
            final TProtNFe.InfProt that = ((TProtNFe.InfProt) object);
            {
                String lhsTpAmb;
                lhsTpAmb = this.getTpAmb();
                String rhsTpAmb;
                rhsTpAmb = that.getTpAmb();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "tpAmb", lhsTpAmb), LocatorUtils.property(thatLocator, "tpAmb", rhsTpAmb), lhsTpAmb, rhsTpAmb)) {
                    return false;
                }
            }
            {
                String lhsVerAplic;
                lhsVerAplic = this.getVerAplic();
                String rhsVerAplic;
                rhsVerAplic = that.getVerAplic();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "verAplic", lhsVerAplic), LocatorUtils.property(thatLocator, "verAplic", rhsVerAplic), lhsVerAplic, rhsVerAplic)) {
                    return false;
                }
            }
            {
                String lhsChNFe;
                lhsChNFe = this.getChNFe();
                String rhsChNFe;
                rhsChNFe = that.getChNFe();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "chNFe", lhsChNFe), LocatorUtils.property(thatLocator, "chNFe", rhsChNFe), lhsChNFe, rhsChNFe)) {
                    return false;
                }
            }
            {
                String lhsDhRecbto;
                lhsDhRecbto = this.getDhRecbto();
                String rhsDhRecbto;
                rhsDhRecbto = that.getDhRecbto();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "dhRecbto", lhsDhRecbto), LocatorUtils.property(thatLocator, "dhRecbto", rhsDhRecbto), lhsDhRecbto, rhsDhRecbto)) {
                    return false;
                }
            }
            {
                String lhsNProt;
                lhsNProt = this.getNProt();
                String rhsNProt;
                rhsNProt = that.getNProt();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "nProt", lhsNProt), LocatorUtils.property(thatLocator, "nProt", rhsNProt), lhsNProt, rhsNProt)) {
                    return false;
                }
            }
            {
                byte[] lhsDigVal;
                lhsDigVal = this.getDigVal();
                byte[] rhsDigVal;
                rhsDigVal = that.getDigVal();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "digVal", lhsDigVal), LocatorUtils.property(thatLocator, "digVal", rhsDigVal), lhsDigVal, rhsDigVal)) {
                    return false;
                }
            }
            {
                String lhsCStat;
                lhsCStat = this.getCStat();
                String rhsCStat;
                rhsCStat = that.getCStat();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "cStat", lhsCStat), LocatorUtils.property(thatLocator, "cStat", rhsCStat), lhsCStat, rhsCStat)) {
                    return false;
                }
            }
            {
                String lhsXMotivo;
                lhsXMotivo = this.getXMotivo();
                String rhsXMotivo;
                rhsXMotivo = that.getXMotivo();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "xMotivo", lhsXMotivo), LocatorUtils.property(thatLocator, "xMotivo", rhsXMotivo), lhsXMotivo, rhsXMotivo)) {
                    return false;
                }
            }
            {
                String lhsId;
                lhsId = this.getId();
                String rhsId;
                rhsId = that.getId();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "id", lhsId), LocatorUtils.property(thatLocator, "id", rhsId), lhsId, rhsId)) {
                    return false;
                }
            }
            return true;
        }

        public boolean equals(Object object) {
            final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
            return equals(null, null, object, strategy);
        }

        public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
            int currentHashCode = 1;
            {
                String theTpAmb;
                theTpAmb = this.getTpAmb();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "tpAmb", theTpAmb), currentHashCode, theTpAmb);
            }
            {
                String theVerAplic;
                theVerAplic = this.getVerAplic();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "verAplic", theVerAplic), currentHashCode, theVerAplic);
            }
            {
                String theChNFe;
                theChNFe = this.getChNFe();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "chNFe", theChNFe), currentHashCode, theChNFe);
            }
            {
                String theDhRecbto;
                theDhRecbto = this.getDhRecbto();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "dhRecbto", theDhRecbto), currentHashCode, theDhRecbto);
            }
            {
                String theNProt;
                theNProt = this.getNProt();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "nProt", theNProt), currentHashCode, theNProt);
            }
            {
                byte[] theDigVal;
                theDigVal = this.getDigVal();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "digVal", theDigVal), currentHashCode, theDigVal);
            }
            {
                String theCStat;
                theCStat = this.getCStat();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "cStat", theCStat), currentHashCode, theCStat);
            }
            {
                String theXMotivo;
                theXMotivo = this.getXMotivo();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "xMotivo", theXMotivo), currentHashCode, theXMotivo);
            }
            {
                String theId;
                theId = this.getId();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "id", theId), currentHashCode, theId);
            }
            return currentHashCode;
        }

        public int hashCode() {
            final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
            return this.hashCode(null, strategy);
        }

    }

}
